name = "secret-sharing-app"
compatibility_date = "2023-01-01"

[[kv_namespaces]]
binding = "SECRETS_KV"
id = "38704694eb004abaa481d4b52ec426b4"

[vars]
# No need to define MASTER_SERVER_KEY here; it’s a secret

